import{a as u,S as y,i as l}from"./assets/vendor-ee72e1a4.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const d of s.addedNodes)d.tagName==="LINK"&&d.rel==="modulepreload"&&a(d)}).observe(document,{childList:!0,subtree:!0});function i(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerPolicy&&(s.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?s.credentials="include":e.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function a(e){if(e.ep)return;e.ep=!0;const s=i(e);fetch(e.href,s)}})();const h="29243392-4dbc80ece43085fc7952f4964",b="https://pixabay.com/api/";async function p({page:r=1,per_page:t=15,q:i=""}={}){try{return(await u.get(b,{params:{page:r,per_page:t,q:i,key:h}})).data}catch(a){throw console.error("Error fetching images:",a),a}}function f(r){const t=document.querySelector(".image-list"),i=r.map(e=>`<li class="gallery-item">
      <a href="${e.largeImageURL}" class="gallery-link" data-lightbox="gallery">
              <div class="image-wrapper">
                <img src="${e.webformatURL}" alt="${e.tags}" class="gallery-image" />
              </div>
              <div class="image-info">
                <p class="info-item"><b>Likes</b> ${e.likes}</p>
                <p class="info-item"><b>Views</b> ${e.views}</p>
                <p class="info-item"><b>Comments</b> ${e.comments}</p>
                <p class="info-item"><b>Downloads</b> ${e.downloads}</p>
              </div>
            </a>
          </li>`).join("");t.insertAdjacentHTML("beforeend",i),new y(".gallery-link",{captionsData:"alt",captionDelay:0}).refresh()}const g=document.querySelector(".form"),L=document.querySelector(".form-input"),c=document.querySelector(".loader"),w=document.querySelector(".image-list"),n=document.querySelector(".btn-more"),o={page:1,per_page:15,q:""};let m=0;g.addEventListener("submit",async r=>{if(r.preventDefault(),o.q=L.value.trim(),o.q===""){l.warning({title:"Warning",message:"Please enter a search term."}),g.reset();return}o.page=1,n.classList.add("hidden"),c.style.display="block",w.innerHTML="";try{const{hits:t,totalHits:i}=await p(o);m=i,t.length===0?l.info({title:"Info",message:"Sorry, there are no images matching your search query. Please try again!"}):(f(t),m>o.page*o.per_page&&n.classList.remove("hidden"))}catch(t){l.error({title:"Error",message:`Something went wrong: ${t.message}`})}finally{c.style.display="none",n.classList.remove("disabled")}});n.addEventListener("click",async()=>{o.page+=1,n.classList.add("disabled"),c.style.display="block";try{const{hits:r}=await p(o);f(r);const t=document.querySelector(".gallery-item"),{height:i}=t.getBoundingClientRect();window.scrollBy({top:i*2,behavior:"smooth"}),o.page*o.per_page>=m&&(l.info({title:"Info",message:"We're sorry, but you've reached the end of search results."}),n.classList.add("hidden"))}catch(r){l.error({title:"Error",message:`Something went wrong: ${r.message}`})}finally{c.style.display="none",n.classList.remove("disabled")}});
//# sourceMappingURL=commonHelpers.js.map
